### ISSUE TITLE
parsedmarc complains about non-supported elasticsearch

### ISSUE THREAD

**Issue by f-zappa** [patschi/parsedmarc-dockerized#1]
Hi,
I'm a bit confused about this - since the elasticsearch version is fixed (to 7.8.1), this should not happen. Maybe I messed up something else? 

parsedmarc_1       | Traceback (most recent call last):
parsedmarc_1       |   File "/opt/pypy/bin/parsedmarc", line 8, in <module>
parsedmarc_1       |     sys.exit(_main())
parsedmarc_1       |   File "/opt/pypy/site-packages/parsedmarc/cli.py", line 583, in _main
parsedmarc_1       |     forensic_indexes=[es_forensic_index])
parsedmarc_1       |   File "/opt/pypy/site-packages/parsedmarc/elastic.py", line 244, in migrate_indexes
parsedmarc_1       |     if not Index(aggregate_index_name).exists():
parsedmarc_1       |   File "/opt/pypy/site-packages/elasticsearch_dsl/index.py", line 414, in exists
parsedmarc_1       |     return self._get_connection(using).indices.exists(index=self._name, **kwargs)
parsedmarc_1       |   File "/opt/pypy/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
parsedmarc_1       |     return func(*args, params=params, headers=headers, **kwargs)
parsedmarc_1       |   File "/opt/pypy/site-packages/elasticsearch/client/indices.py", line 333, in exists
parsedmarc_1       |     "HEAD", _make_path(index), params=params, headers=headers
parsedmarc_1       |   File "/opt/pypy/site-packages/elasticsearch/transport.py", line 413, in perform_request
parsedmarc_1       |     _ProductChecker.raise_error(self._verified_elasticsearch)
parsedmarc_1       |   File "/opt/pypy/site-packages/elasticsearch/transport.py", line 630, in raise_error
parsedmarc_1       |     raise UnsupportedProductError(message)
parsedmarc_1       | elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch
parsedmarc-dockerized_parsedmarc_1 exited with code 1

**Comment by righter83** [comment]
Hey I had the same problem.

I resolved it by changing the docker-composer.yml file
`  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1`

Afterwards it was working

**Comment by m2021acct** [comment]
The solution above works.
