### ISSUE TITLE
Forensic samples dashboard not populated

### ISSUE THREAD

**Issue by hugalafutro** [patschi/parsedmarc-dockerized#12]
Hi, 
the main dashboard works splendidly, however the Forensic samples one is empty with following errors:
![image](https://user-images.githubusercontent.com/30209689/219853638-0871d77a-f00e-4366-8da7-4a40d465ab94.png)
same for `source_country.keyword` & `source_ip_address.keyword`

Any idea if these need to be updated to different values, or is it parsedmarc config that needs to be amended?

Thanks for any insights!

**Comment by GIYItalk** [comment]
> Hi, the main dashboard works splendidly, however the Forensic samples one is empty with following errors: ![image](https://user-images.githubusercontent.com/30209689/219853638-0871d77a-f00e-4366-8da7-4a40d465ab94.png) same for `source_country.keyword` & `source_ip_address.keyword`
> 
> Any idea if these need to be updated to different values, or is it parsedmarc config that needs to be amended?
> 
> Thanks for any insights!

hi, have you solved this problem?

**Comment by hugalafutro** [comment]
Sadly no, I know nothing about elastic so this is literally just me waiting till someone comes along and fixes it for me.

**Comment by GIYItalk** [comment]
> Sadly no, I know nothing about elastic so this is literally just me waiting till someone comes along and fixes it for me.

You can try to edit this dashboard
Then delete this parameter. This parameter may not exist, no data so error

**Comment by hugalafutro** [comment]
But that's the problem - the data is not generated I think. I'll admit here I do not really understand the whole underlaying technology that much, I just like nicely visualized data; so I might be completely off, but when I look into my inbox there are only ever Aggregate DMARC emails in there after they are processed by parsedmarc, never anything in the Forensic folder. So I think the solution is not to edit the dashboard, but to find out why the forensic data is not generated.

But since I don't understand the components I am not sure whether it is one or any of these (and even if I did I still wouldn't know what to do haha, but it'd be a starting point):
- issue with my mailcow-dockerized server's rspamd not generating the dmarc reports correctly
- parsedmarc's config not configured to generate the forensic data
- issue with the elastic/kibana stack

I mean I don't even know how the forensic dashboard is supposed to look like or what it's good for, but I liked the look of the main dashboard and was wondering what the other one is like.

**Comment by hugalafutro** [comment]
@GIYItalk The dashboard is correct, there just isn't any forensic data as it is apparently privacy sensitive, found this @ https://domainaware.github.io/parsedmarc/#dmarc-forensic-samples

> If your legitimate outgoing email fails DMARC, it is possible that email may appear later in a forensic report. 
> Forensic reports contain the original headers of an email that failed a DMARC check, and sometimes may also include the full message body, depending on the policy of the reporting organization.
> Most reporting organizations do not send forensic reports of any kind for privacy reasons. While aggregate DMARC reports are sent at least daily, it is normal to receive very few forensic reports.

so I'm closing this as there is nothing wrong with the dashboard - it can't display data that doesn't exist.
