### ISSUE TITLE
Elastic 7.17.9, 8.5.0 and 8.6.1 Security Update

### ISSUE THREAD

**Issue by toto4ds** [patschi/parsedmarc-dockerized#18]
Affected Versions:
Kibana Versions 7.0.0 through 7.17.8 and 8.0.0 through 8.6.0

https://discuss.elastic.co/t/elastic-7-17-9-8-5-0-and-8-6-1-security-update/324661

**Comment by patschi** [comment]
Fixed via #25 and #26. Using 7.17.18 for now as it doesn't break compatibility with existing setups, as 8.x requires a middle step to 7.17.9 it seems. Closing this one now.
