### ISSUE TITLE
Fresh install do not work

### ISSUE THREAD

**Issue by renoproc** [patschi/parsedmarc-dockerized#6]
Hi, I've a fresh installation on a ZorinOS 16 (20.04.1-Ubuntu), connexion to https://myIP:9999 show the elasticsearch dashbord, with all boards in error (SPF, DKIM, DMARC...) and complains about a warning
```
Configuration missing
server.publicBaseUrl is missing and should be configured when running in a production environment. Some features may not behave correctly.
```
The second error at the bottom, sounds logical because elasticsearch didn't receive the dmarc data
`No matching indices found: No indices match pattern "dmarc_aggregate*"`

As you can see in this screen capture
![Screen capture 2022-08-16 14-58-40](https://user-images.githubusercontent.com/884189/184885561-eb6a265a-3fee-4c88-9432-1dd585d37fc3.png)

my config.ini
```
[general]
save_aggregate = True
save_forensic = True
log_file = /var/log/parsedmarc/

[imap]
# IMAP login
host = imap.gmail.com
port = 993
user = my_address@gmail.com
password = "my password"
ssl = True

# advanced
[mailbox]
watch = True
reports_folder = DMARC
archive_folder = DmarcProcessed
delete = False

# advanced advanced
test = True

### NO EDIT REQURIED DOWN BELOW
[elasticsearch]
hosts = elasticsearch:9200
ssl = False
```
Folder for the log file is root ownered, but nothing recorded
I tried with the debug = True option in the config.ini, no more information

docker do not complain during the initialization process
```
/opt/patschi_parsedmarc-dockerized# docker-compose up -d
Creating network "patschi_parsedmarc-dockerized_parsedmarc-network" with driver "bridge"
Creating network "patschi_parsedmarc-dockerized_default" with the default driver
Creating patschi_parsedmarc-dockerized_geoipupdate_1     ... done
Creating patschi_parsedmarc-dockerized_parsedmarc-init_1 ... done
Creating patschi_parsedmarc-dockerized_elasticsearch_1   ... done
Creating patschi_parsedmarc-dockerized_parsedmarc_1      ... done
Creating patschi_parsedmarc-dockerized_kibana_1          ... done
Creating patschi_parsedmarc-dockerized_nginx_1           ... done
```

Did I missed something ?
Thanks in advance

**Comment by xpufx** [comment]
Check the logs for the parsedmarc container. I am getting a whole lot of messages about deprecated config options. They are supposed to go into a new [mailbox] section apparently. (I mean if these are really deprecated you would not be collecting any data)

**Comment by patschi** [comment]
I do really appreciate all your help here. I suppose it has been fixed by now, so closing it.

The new config example has the setting at the new `[mailbox]` section and the `nameserver` entry to raise awareness that it can be changed.
