### ISSUE TITLE
O365 imap failing

### ISSUE THREAD

**Issue by frank3427** [patschi/parsedmarc-dockerized#7]
in my setup I have O365 as a servers adn with O365 disabling basic Auth I am getting login failures, parcedmarc can not loging to email account using iMAP

**Comment by patschi** [comment]
parsedmarc needs access to your emails using IMAP. If it's not possible, you can't use parsedmarc. Reach out to Microsoft or check any options you can adjust to enable IMAP access again. That's nothing I can help you with.

Also, this is not related to the docker image.
