### ISSUE TITLE
empty json output file generated

### ISSUE THREAD

**Issue by jahlives** [patschi/parsedmarc-dockerized#9]
I'm using the following command to start parsedmarc in docker-compose

```
command: ["-c", "/etc/parsedmarc.ini", "--verbose", "-o", "/output", "--aggregate-json-filename", "/output/aggregate.json", "--forensic-json-filename", "/output/forensic.json", "--debug"]
```
it is stored perfectly into opensearch but I assumed that the local files would be created too. But the json files just contain `[]` after a report is processed. Also the csv files do not look complete.  Debug does not show an error related to writing into the files.

**Comment by patschi** [comment]
I think you're more looking for help in the [original upstream project](https://github.com/domainaware/parsedmarc/issues) and not this docker pre-packed project. Please raise queries above. Closing this one.
